### ISSUE TITLE
Add Swagger definitions

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/EventGate#20]
## Background
Add Swagger definitions. AWS GateWay should support something already. 

## Feature
Add Swagger definitions

**Comment by ABMC831** [comment]
What is inside AWS Gateway does not seem entirely suitable
mostly exposes what endpoints are available - for us public one is blocked by SCP anyway
and for actual resources, all are listed as passthrough since they are handled by lambda... also auth, from gateway point of view there isn't one (as that would be AWS sigv4a) just later lambda handles jwt and its validation

meaning: most probably we expose yet another resource, which would be osa3 definition provided by lambda itself
